sudo: required
services:
    - docker

before_install:
    - docker build -t sirasaoa/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true sirasaoa/react-test npm run test -- --coverage

after_success:
    - docker build -t sirasaoa/multi-client ./client
    - docker build -t sirasaoa/multi-nginx ./nginx
    - docker build -t sirasaoa/multi-server ./server
    - docker build -t sirasaoa/multi-worker ./worker

    #Log in to the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    #Push images to Docker Hub
    - docker push sirasaoa/multi-client
    - docker push sirasaoa/multi-nginx
    - docker push sirasaoa/multi-server
    - docker push sirasaoa/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: multiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-233873002529
    bucket_path: multi-docker
    on:
        branch: master
    access_key_id : $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
